version: 1.1.{build}-{branch}

build: false

environment:
  matrix:
    - MINICONDA: "C:\\Miniconda3"
      PYTHON_ARCH: "32"
      platform: x86

    - MINICONDA: "C:\\Miniconda3"
      PYTHON_ARCH: "32"
      platform: x64

    - MINICONDA: "C:\\Miniconda3"
      PYTHON_ARCH: "64"
      platform: x64

    - MINICONDA: "C:\\Miniconda35"
      PYTHON_ARCH: "32"
      platform: x86

    - MINICONDA: "C:\\Miniconda35"
      PYTHON_ARCH: "32"
      platform: x64

    - MINICONDA: "C:\\Miniconda35"
      PYTHON_ARCH: "64"
      platform: x64

init:
  - "ECHO %PYTHON% %PYTHON_ARCH%" %PYTHON_VERSION% %MINICONDA%"

install:
  - "%MINICONDA%/Scripts/pip.exe install pytelemetry docopt sortedcontainers pyqtgraph"
  - "%MINICONDA%/Scripts/conda install numpy -y"
  - "%MINICONDA%/Scripts/conda install PyQt4"
  - "%MINICONDA%/Scripts/conda install pytest-cov"
  - "cd %APPVEYOR_BUILD_FOLDER%"
test_script:
  - "%MINICONDA%/Scripts/py.test --cov"
